//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class AddForceCmd : ICommand{
	private string[] help = {
		"/addForce <ID> <ForceX> <ForceY> <ForceZ> - Forces a player in a direction",
		"/addForce * <ForceX> <ForceY> <ForceZ> - Forces all players in a direction",
		"/addForce + <ForceX> <ForceY> <ForceZ> - Forces everyone but you in a direction"
	};
	public bool cmd (string[] args, FengGameManagerMKII gm){
		if (args.Length == 0){
			ModMain.instance.sendToPlayer(this.help);
			return true;
		}
		object[] param = new object[]{new Vector3(float.Parse(args[1]), float.Parse(args[2]), float.Parse(args[3]))};

		switch(args[0][0]){
			case '*':
				foreach (HERO hero in GameObject.FindObjectsOfType<HERO>()){
					hero.photonView.RPC("blowAway", hero.photonView.owner, param);
				}
				return true;
			case '+':
				foreach (HERO hero in GameObject.FindObjectsOfType<HERO>()){
					if (hero.photonView.ownerId != PhotonNetwork.player.ID){
						hero.photonView.RPC("blowAway", hero.photonView.owner, param);
					}
				}
				return true;
			default:
				int pid = int.Parse(args[0]);
				foreach (HERO hero in GameObject.FindObjectsOfType<HERO>()){
					if (hero.photonView.ownerId == pid){
						hero.photonView.RPC("blowAway", hero.photonView.owner, param);
					}
				}
				return true;
		}
	}

    public string getDescriptionString() {
        return "Adds a force to a player.";
    }
}

