//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class ChampionshipCmd : ICommand{

	private string[] help = new string[]{
		"/ch info",
		"/ch start",
		"/ch stop"
	};

	public bool cmd (string[] args, FengGameManagerMKII gm){
		if (args.Length == 0){
			ModMain.instance.sendToPlayer(this.help);
			return true;
		}

		if (args[0].Equals("info", StringComparison.OrdinalIgnoreCase)){
			CManager cm = ModMain.instance.getChampionshipManager();
			ModMain.instance.sendToPlayer("Is running? " + cm.isRunning);
			ModMain.instance.sendToPlayer("is in match? " + cm.isInMatch());
			ModMain.instance.sendToPlayer(cm.getInfoString());
			return true;
		}

		if (args[0].Equals("start", StringComparison.OrdinalIgnoreCase)){
			ModMain.instance.getChampionshipManager().start();
			return true;
		}

		if (args[0].Equals("stop", StringComparison.OrdinalIgnoreCase)){
			ModMain.instance.getChampionshipManager().stop();
			return true;
		}
		
		ModMain.instance.sendToPlayer("Command not recognized: " + args[0]);
		ModMain.instance.sendToPlayer(this.help);
		return true;
	}

    public string getDescriptionString() {
        return "Controls the parameters for the championship/duel mode.";
    }

}

