//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
#if DEBUG
using System;
public class DebugCmd : ICommand{
	private string[] help = {
		"/debug <on|off>",
		"/debug mode <File|Chat>",
		"/debug info"
	};
	public bool cmd (string[] args, FengGameManagerMKII gm){
		if (args.Length == 0){
			ModMain.instance.sendToPlayer(this.help);
			return true;
		}
		if (args[0].Equals("mode", StringComparison.OrdinalIgnoreCase)){
			if (args[1].Equals("file", StringComparison.OrdinalIgnoreCase)){
				ModMain.instance.debugMode = ModMain.DebugMode.FILE;
				return true;
			}else if (args[1].Equals("chat", StringComparison.OrdinalIgnoreCase)){
				ModMain.instance.debugMode = ModMain.DebugMode.CHAT;
				return true;
			}else{
				return false;
			}
		}else if (args[0].Equals("info", StringComparison.OrdinalIgnoreCase)){
			ModMain.instance.sendToPlayer("Debug on: " + ModMain.instance.debugEnabled + "\n" +
				"Debug mode: " + ModMain.instance.debugMode);
			return true;
		}else if (args[0].Equals("on", StringComparison.OrdinalIgnoreCase)){
			ModMain.instance.debugEnabled = true;
			return true;
		}else if (args[0].Equals("off", StringComparison.OrdinalIgnoreCase)){
			ModMain.instance.debugEnabled = false;
			return true;
		}else {
			ModMain.instance.sendToPlayer(this.help);
			return true;
		}
	}

    public string getDescriptionString() {
        return "DEBUG U BITCH";
    }
}

#endif

