//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class FloodCmd : ICommand{
	public bool cmd (string[] args, FengGameManagerMKII gm){
		return false;
	}

    public string getDescriptionString() {
        return "Floods the chat.";
    }
}

