//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class HorseCmd : ICommand{

	public bool cmd (string[] args, FengGameManagerMKII gm){
		HERO hero = null;
		foreach(HERO h in GameObject.FindObjectsOfType<HERO>()){
			if (h.photonView.isMine){
				hero = h;
				break;
			}
		}

		if (hero == null){
			ModMain.instance.sendToPlayer("You\'re not alive.");
		}else{
			GameObject horse = PhotonNetwork.Instantiate("horse", hero.gameObject.transform.position, Quaternion.Euler(0F,0F,0F), 0);
			horse.GetComponent<Horse>().myHero = hero.gameObject;
		}

		return true;
	}

    public string getDescriptionString() {
        return "Spawns a horse.";
    }
}

