//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class RawCmd : ICommand{

	public bool cmd (string[] args, FengGameManagerMKII gm){
		ModMain.instance.getGameManager().photonView.RPC("Chat", PhotonTargets.All, new object[]{string.Join(" ", args), string.Empty});
		return true;
	}

    public string getDescriptionString() {
        return "Sends a raw message to everyone.";
    }
}

