//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class RoomCmd : ICommand{
	private string[] help = new string[]{
		"/room info",
		"/room players <PlayerCount>",
		"/room visible <true|false>",
		"/room open <true|false>",
	};

	//Room name = <RoomName>`<Map name>`<difficulty>`<GameTime>`<DayTime>``<RandomInt>

	public bool cmd (string[] args, FengGameManagerMKII gm){
		if (args.Length == 0){
			ModMain.instance.sendToPlayer(this.help);
			return true;
		}

		if (args[0].Equals("info", StringComparison.OrdinalIgnoreCase)){
			this.sendInfo();
			return true;
		}else if(args[0].Equals("players", StringComparison.OrdinalIgnoreCase)){
			PhotonNetwork.room.maxPlayers = int.Parse(args[1]);
			return true;
		}else if(args[0].Equals("visible", StringComparison.OrdinalIgnoreCase)){
			PhotonNetwork.room.visible = args[1].Equals("true", StringComparison.OrdinalIgnoreCase);
			return true;
		}else if(args[0].Equals("open", StringComparison.OrdinalIgnoreCase)){
			PhotonNetwork.room.open = args[1].Equals("true", StringComparison.OrdinalIgnoreCase);
			return true;
		}else{
			ModMain.instance.sendToPlayer(this.help);
			return true;
		}
	}
	//room name <newName>
	private void setRoomName(string[] args){
		string[] original = PhotonNetwork.room.name.Split('`');
		string[] nameParts = new string[args.Length -1];

		Array.Copy(args, 1, nameParts, 0, nameParts.Length);
		original[0] = string.Join(" ", nameParts);
		
		//PhotonNetwork.room.name = string.Join("`", original);
	}

	private void sendInfo(){
		Room room = PhotonNetwork.room;
		string[] message = new string[]{
			"Room name: " + room.name,
			"Players: " + room.playerCount + "/" +room.maxPlayers,
			"Is open: " + room.open,
			"Is visible: " + room.visible,
		};
		ModMain.instance.sendToPlayer(message);
	}

    public string getDescriptionString() {
        return "Controls the room parameters.";
    }
}

