//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class StealCmd : ICommand{
	public bool cmd (string[] args, FengGameManagerMKII gm){
		if (!PhotonNetwork.isMasterClient){
			PhotonPlayer oldMC = PhotonNetwork.masterClient;
			CrashCmd.doCrash(oldMC, 2, 512, "restartGameByClient");
			PhotonNetwork.SetMasterClient(PhotonNetwork.player);
			PhotonNetwork.CloseConnection(oldMC);
		}

		return true;
	}

    public string getDescriptionString() {
        return "(Broken) Steals the MC.";
    }
}

