//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class PlayerData{
	private int kills;
	private int totalDamage;
	private int wins;
	private int losses;

	public int Kills {
		get {
			return this.kills;
		}
		set {
			kills = value;
		}
	}

	public int TotalDamage {
		get {
			return this.totalDamage;
		}
		set {
			totalDamage = value;
		}
	}

	public int Wins {
		get {
			return this.wins;
		}
		set {
			wins = value;
		}
	}

	public int Losses {
		get {
			return this.losses;
		}
		set {
			losses = value;
		}
	}
}

